name: guarded_go_router
description: This package aims to provide a guard mechanism to a project using go_router and riverpod
repository: https://github.com/harkairt/guarded_go_router
version: 0.0.5

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.2"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  go_router: ^13.0.1
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mocktail: ^1.0.1
